#!/usr/bin/python3
import sys
import glob
import html
import os
import urllib.parse

args = sys.argv

if len(args) < 2:
    print('usage: {} <directory>'.format(args[0]), file=sys.stderr)
    sys.exit(1)

template = '''
<html>
<head>
<meta charset="utf-8">
</head>
<body>
<ul>
{}
</ul>
</body>
</html>
'''

base = args[1].rstrip('/')
pat = base + '/**/*.md'
s = ''
for f in glob.glob(pat, recursive=True):
    rel = os.path.relpath(f, base)
    href = urllib.parse.quote(rel)
    text = html.escape(rel)
    s += '<li><a href="{}">{}</a></li>'.format(href, text)
print(template.format(s))
